#!/bin/bash
SERVER='https://hastebin.com'

API_ENDPOINT="$SERVER/documents"

function printUsage() {
    cat << EOF
Usage: $0 [-h] [-- <files>]

  Options:

    -h

      Print this help message and exit successfully

    -- <files>

      All arguments following a '--' will be treated as filenames. Each file
      will be uplaoded separately, and URLs will be returned separated by
      newlines. If this argument is not present, STDIN will be uploaded
      instead.
EOF
}


function doUpload() {
    curl -s -X POST -d '@-' "$API_ENDPOINT" \
        | sed  -E '
            #Extract document key from json. This properly handles escaped
            #quotation marks, even though I expect they will never be present.

            s#^\{"key":"(([^"]|\\")+)"\}$#\1#g

            #Unescape escaped quotation marks

            s#\\"#"#g

            #Append newline to the end, because haste doesnt include one.
            s#$#\n#g

            #Prepend server URL

        '"  s#^#$SERVER/#g "
}


if [[ "$#" -gt 0 ]]; then
    #Process args.
    #If the '--' argument is encountered, all other args are treated as files
    #to be uploaded
    arg_processing_mode=normal
    for arg in "$@"; do
        case $arg_processing_mode in
            normal)
                case "$arg" in
                    --)
                        arg_processing_mode=upload
                        ;;
                    *)
                        printUsage
                        exit 0
                        ;;
                esac
                ;;
            upload)
                doUpload < "$arg"
                ;;
            *)
                echo "Error: Unknown arg processing state" 1>&2
                exit 1
                ;;
        esac
    done
else
    doUpload
fi
